// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn3XvpLm-HrjgjExdXEDs5LjOSLPpbIEY',
    appId: '1:294303509902:web:44802ed90e0d82c900c8df',
    messagingSenderId: '294303509902',
    projectId: 'develop59-6ec57',
    authDomain: 'develop59-6ec57.firebaseapp.com',
    storageBucket: 'develop59-6ec57.firebasestorage.app',
    measurementId: 'G-8F58SXEPJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPotdcD1qfDlVnQYRdSrJ8NlDi6_9pwlI',
    appId: '1:294303509902:android:74dbdb43e059ed1600c8df',
    messagingSenderId: '294303509902',
    projectId: 'develop59-6ec57',
    storageBucket: 'develop59-6ec57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8MfB1BHRIgTaMTw0BOrMbvzYX1kV9kQs',
    appId: '1:294303509902:ios:2b83cc2fef348fe500c8df',
    messagingSenderId: '294303509902',
    projectId: 'develop59-6ec57',
    storageBucket: 'develop59-6ec57.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiCdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8MfB1BHRIgTaMTw0BOrMbvzYX1kV9kQs',
    appId: '1:294303509902:ios:2b83cc2fef348fe500c8df',
    messagingSenderId: '294303509902',
    projectId: 'develop59-6ec57',
    storageBucket: 'develop59-6ec57.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiCdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn3XvpLm-HrjgjExdXEDs5LjOSLPpbIEY',
    appId: '1:294303509902:web:79c554c7266f351100c8df',
    messagingSenderId: '294303509902',
    projectId: 'develop59-6ec57',
    authDomain: 'develop59-6ec57.firebaseapp.com',
    storageBucket: 'develop59-6ec57.firebasestorage.app',
    measurementId: 'G-F9NG9Z55SP',
  );

}
